export const ADD_PLOT = "ADD_PLOT";
export const UPDATE_PLOT = "UPDATE_PLOT";
export const GET_PLANETS = "GET_PLANETS";
export const GET_PLANETS_SUCCESS = "GET_PLANETS_SUCCESS";
export const RESET_PLANETS = "RESET_PLANETS";
export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const RESET_CHARACTERS = "RESET_CHARACTERS";